site_name: Meshcore Wielkopolska
site_description: Lokalna wiki Wielkopolskiej Społeczności MeshCore
site_url: https://mcwlkp.pl/
use_directory_urls: true

repo_url: https://github.com/chybaDapi/awesome-meshcore-wlkp
edit_uri: edit/main/docs/

theme:
  name: material
  language: pl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit

nav:
  - Start: index.md
  - Szybki start: quickstart.md
  - Presety: presets.md
  - Kanały: channels.md
  - Boty: bots.md
  - Repeatery: repeaters.md
  - Regionalizacja: regions.md
  - Lokalne narzędzia: tools.md
  - Przydatne linki: resources.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search:
      lang: pl
